### ISSUE TITLE
Summary Not Avaible

### ISSUE THREAD

**Issue by 4D3K** [starlilyth/Linux-PoolManager#4] opened 2014-03-03 15:57 UTC
At farm view I don't see all information - every node has Version, Runtime, Hashrate, WU, Rej, HW, but there is no info - Version is "uknown" and below the rest is "Summary Not Avaible". When I choose node details all information are ok, the problem is only with farm view.

**Comment by starlilyth** [comment] 2014-03-03 16:30
Make sure mgpumon and broadcast are stopped. Edit bamt.conf, set do_mgpumon to 0 and set do_bcast_status to 0. If you need to use mgpumon, put it on a different port.

**Comment by 4D3K** [comment] 2014-03-03 17:13
I did what you suggested and still the same problem, but it helped with double nodes...

**Comment by starlilyth** [comment] 2014-03-03 17:25
Plain BAMT nodes will report basic information to Farmview, but will not have all the details. Do the nodes that are not reporting all information have PoolManager on them?

**Comment by 4D3K** [comment] 2014-03-03 17:40
yes, I've updated all nodes to the latest pool manager, so now all nodes are bamt 1.2 with your pool manager. All nodes in farm overview don't have mentioned information (Version, Runtime, Hashrate, WU, Rej, HW).
![node](https://f.cloud.github.com/assets/6841156/2312342/e55d2af6-a2fa-11e3-8c20-611b4daefa98.png)

**Comment by starlilyth** [comment] 2014-03-03 17:55
The nodes will also need 'do_bcast_status' set to 0 in bamt.conf, so the default BAMT status reporting isnt being sent to FarmView.

**Comment by 4D3K** [comment] 2014-03-03 18:06
it is set to 0, as I wrote few posts before. Once again: all nodes are bamt 1.2 with latest pool manager and have do_mgpumon and do_bcast_status set to 0.

**Comment by 4D3K** [comment] 2014-03-03 18:10
when I choose node details I have 
![nodedetails](https://f.cloud.github.com/assets/6841156/2312664/11bf95b2-a2ff-11e3-99f9-302b7bfc958e.png)

**Comment by starlilyth** [comment] 2014-03-03 18:36
The data sent to farmview is pulled separately from the data on status.pl, with a different script. The most common issue is a conflict with the BAMT scripts, but its clear you have eliminated that. 

It is getting pool data to Farmview, so it is getting data from the right source, but it is incomplete. Its clear the data is available, because status.pl can get it, so I am not sure what the problem is. 

There are likely some relevant errors in /tmp/apache2/error.log and /var/log/messages. Please take a look and see if there is anything from sendstatus.pl in either. 

Thank you! 
Lily

**Comment by 4D3K** [comment] 2014-03-03 19:13
no errors in both logs

**Comment by starlilyth** [comment] 2014-03-04 18:48
Can you try run sendstatus.pl directly? Go to /opt/ifmi and execute it as root. You may have to chmod +x it. If it produces any errors, please show them here. Thanks!

**Comment by 4D3K** [comment] 2014-03-04 20:03
I changed chmod +x and run ./sendstatus.pl, but nothing happened. Just next promt line.

**Comment by starlilyth** [comment] 2014-03-04 20:24
I am sure you have tried this, but I am asking to be certain: have you killed farmview and let it start again?

**Comment by 4D3K** [comment] 2014-03-05 08:37
I didn't kill but I'm sure I did some restarts. To be sure I killed farmview and I can see its process starts after few sec, but no change - the same data is missing.
There must be something. I found someone else has similar problem here:
https://litecointalk.org/index.php?topic=14094.msg125284#msg125284
but he has only one node without info and my all nodes are missing info...

**Comment by 4D3K** [comment] 2014-03-05 08:43
what I noticed is that the guy at litecointalk has sgminer - please notice the version - 4.0, so he propably is using newer bamt version.

**Comment by starlilyth** [comment] 2014-03-07 00:37
I have made some changes in the way summary and version data is sent to farmview, hopefully this will fix up this issue. Please try it out and let me know.

**Comment by 4D3K** [comment] 2014-03-10 09:52
still no luck
![ifmi](https://f.cloud.github.com/assets/6841156/2372365/a948c7c0-a839-11e3-8fd4-c8d10d8c2406.JPG)

**Comment by 4D3K** [comment] 2014-03-10 09:55
![ifmi2](https://f.cloud.github.com/assets/6841156/2372405/22ad861e-a83a-11e3-95ae-0725aff9b8c6.JPG)
<...cut....>

![ifmi3](https://f.cloud.github.com/assets/6841156/2372407/24bdd968-a83a-11e3-9d64-ac91d4e416af.JPG)

**Comment by starlilyth** [comment] 2014-03-12 08:32
This issue has been reported by several people now, and is the next item I will be working on. 
I have a good idea about the cause, so this should be solved soon.

**Comment by starlilyth** [comment] 2014-03-12 17:05
I have made a small change to FarmView, please test and see if this solves your issue.

**Comment by starlilyth** [comment] 2014-03-13 21:49
I have several reports that this condition is now fixed. Closing.

**Closed as completed by starlilyth** 2014-03-13 21:49 UTC
Labels: bug
